"""'users'

Revision ID: 458900c57101
Revises: 
Create Date: 2022-02-23 21:04:38.826449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458900c57101'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User name', sa.String(length=200), nullable=False),
    sa.Column('E.Mail', sa.String(length=200), nullable=False),
    sa.Column('Password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('E.Mail'),
    sa.UniqueConstraint('Password'),
    sa.UniqueConstraint('User name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
